blog: Kronos - Run easily ABAP code for free in 5 minutes
codbex/codbex.github.io pull request #4
Opened 2024-06-26 12:15 UTC by iliyan-velichkov

2024-06-26 12:46 UTC, iliyan-velichkov commented
@delchev @ThuF the PR is for review

2024-06-27 06:58 UTC, delchev requested changes
Awesome!

2024-06-27 06:58 UTC, delchev commented on _posts/2024-06-25-run-abap-for-free.md
> +- you can use any Database supported by codbex Atlas like H2, PostgreSQL, MySQL, Snowflake, HANA, etc.<br>
Atlas -> Kronos

2024-06-27 07:05 UTC, iliyan-velichkov commented on _posts/2024-06-25-run-abap-for-free.md
> +- you can use any Database supported by codbex Atlas like H2, PostgreSQL, MySQL, Snowflake, HANA, etc.<br>
done

2024-06-27 07:51 UTC, merged

2024-06-28 08:42 UTC, iliyan-velichkov commented
official blog link - https://www.codbex.com/technology/2024/06/25/run-abap-for-free/